name: "hello world"

on:
    push:
        branches:
            - master
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Hello"
              run: echo "Hello World"
    
    test:
        runs-on: ububtu-latest
        steps:
            - name: "Printing Date"
              run: echo $(date)
