name: "hello world"

on:
    push:
        branches:
            - master
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Hello"
              run: echo "Hello World"

            - name: "Printing Date"
              run: echo $(date)

    configuring_docker:
        runs-on: ubuntu-latest
        steps:

            - name: "Installing updates"
              run: sudo apt update

            - name: "Installing Containerd"
              run: sudo apt install containerd -y
             
            - name: "Installing docker"
              run: sudo apt install docker.io -y

            - name: "Starting docker service"
              run: sudo systemctl start docker
    
            - name: "Pulling docker image"
              run: sudo docker pull centos:latest

            - name: "Listing docker images"
              run: sudo docker images

            - name: "Running container"
              run: sudo docker run -dit --name MYCONT1 centos:latest

            - name: "Listing containers"
              run: sudo docker ps -a
